In [441]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import mpl_toolkits
%matplotlib inline

In [442]:
data = pd.read_csv("data/monsters.csv")

In [443]:
data.head()

,Unnamed: 0,_id,index,name,size,type,subtype,alignment,armor_class,hit_points,...,condition_immunities,senses,languages,challenge_rating,special_abilities,actions,legendary_actions,url,reactions,other_speeds
0,0,5f2329ad0b1bb138c59411ee,aboleth,Aboleth,Large,aberration,NaN,lawful evil,17,135,...,[],"{'darkvision': '120 ft.', 'passive_perception'...","Deep Speech, telepathy 120 ft.",10.00,"[{'name': 'Amphibious', 'desc': 'The aboleth c...","[{'name': 'Multiattack', 'desc': 'The aboleth ...","[{'name': 'Detect', 'desc': 'The aboleth makes...",/api/monsters/aboleth,NaN,NaN
1,1,5f2329ad0b1bb138c59411ef,acolyte,Acolyte,Medium,humanoid,any race,any alignment,10,9,...,[],{'passive_perception': 12},any one language (usually Common),0.25,"[{'name': 'Spellcasting', 'desc': 'The acolyte...","[{'name': 'Club', 'desc': 'Melee Weapon Attack...",NaN,/api/monsters/acolyte,NaN,NaN
2,2,5f2329ad0b1bb138c59411f1,adult-black-dragon,Adult Black Dragon,Huge,dragon,NaN,chaotic evil,19,195,...,[],"{'blindsight': '60 ft.', 'darkvision': '120 ft...","Common, Draconic",14.00,"[{'name': 'Amphibious', 'desc': 'The dragon ca...","[{'name': 'Multiattack', 'desc': 'The dragon c...","[{'name': 'Detect', 'desc': 'The dragon makes ...",/api/monsters/adult-black-dragon,NaN,NaN
3,3,5f2329ad0b1bb138c59411f0,adult-blue-dragon,Adult Blue Dragon,Huge,dragon,NaN,lawful evil,19,225,...,[],"{'blindsight': '60 ft.', 'darkvision': '120 ft...","Common, Draconic",16.00,"[{'name': 'Legendary Resistance', 'desc': 'If ...","[{'name': 'Multiattack', 'desc': 'The dragon c...","[{'name': 'Detect', 'desc': 'The dragon makes ...",/api/monsters/adult-blue-dragon,NaN,NaN
4,4,5f2329ad0b1bb138c59411f2,adult-brass-dragon,Adult Brass Dragon,Huge,dragon,NaN,chaotic good,18,172,...,[],"{'blindsight': '60 ft.', 'darkvision': '120 ft...","Common, Draconic",13.00,"[{'name': 'Legendary Resistance', 'desc': 'If ...","[{'name': 'Multiattack', 'desc': 'The dragon c...",NaN,/api/monsters/adult-brass-dragon,NaN,NaN

In [444]:
data.describe()

,Unnamed: 0,armor_class,hit_points,strength,dexterity,constitution,intelligence,wisdom,charisma,challenge_rating
count,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000
mean,160.500000,14.031056,81.291925,15.161491,12.624224,15.080745,7.754658,11.686335,9.683230,4.543090
std,93.097619,3.256285,99.425430,6.736612,3.202185,4.506105,5.704460,2.934020,5.789584,5.892224
min,0.000000,5.000000,1.000000,1.000000,1.000000,8.000000,1.000000,3.000000,1.000000,0.000000
25%,80.250000,12.000000,18.250000,11.000000,10.000000,12.000000,2.000000,10.000000,5.000000,0.500000
50%,160.500000,13.000000,45.000000,16.000000,13.000000,14.000000,7.000000,12.000000,8.000000,2.000000
75%,240.750000,17.000000,114.000000,19.000000,15.000000,18.000000,12.000000,13.000000,14.000000,6.000000
max,321.000000,25.000000,676.000000,30.000000,28.000000,30.000000,25.000000,25.000000,30.000000,30.000000

In [445]:
# data = data[data.legendary_actions.notna() == False]
# data = data[data.special_abilities.notna() == False]

data.legendary_actions = data.legendary_actions.notna().mul(1)
data.special_abilities = data.special_abilities.notna().mul(1)

In [446]:
data.head()

,Unnamed: 0,_id,index,name,size,type,subtype,alignment,armor_class,hit_points,...,condition_immunities,senses,languages,challenge_rating,special_abilities,actions,legendary_actions,url,reactions,other_speeds
0,0,5f2329ad0b1bb138c59411ee,aboleth,Aboleth,Large,aberration,NaN,lawful evil,17,135,...,[],"{'darkvision': '120 ft.', 'passive_perception'...","Deep Speech, telepathy 120 ft.",10.00,1,"[{'name': 'Multiattack', 'desc': 'The aboleth ...",1,/api/monsters/aboleth,NaN,NaN
1,1,5f2329ad0b1bb138c59411ef,acolyte,Acolyte,Medium,humanoid,any race,any alignment,10,9,...,[],{'passive_perception': 12},any one language (usually Common),0.25,1,"[{'name': 'Club', 'desc': 'Melee Weapon Attack...",0,/api/monsters/acolyte,NaN,NaN
2,2,5f2329ad0b1bb138c59411f1,adult-black-dragon,Adult Black Dragon,Huge,dragon,NaN,chaotic evil,19,195,...,[],"{'blindsight': '60 ft.', 'darkvision': '120 ft...","Common, Draconic",14.00,1,"[{'name': 'Multiattack', 'desc': 'The dragon c...",1,/api/monsters/adult-black-dragon,NaN,NaN
3,3,5f2329ad0b1bb138c59411f0,adult-blue-dragon,Adult Blue Dragon,Huge,dragon,NaN,lawful evil,19,225,...,[],"{'blindsight': '60 ft.', 'darkvision': '120 ft...","Common, Draconic",16.00,1,"[{'name': 'Multiattack', 'desc': 'The dragon c...",1,/api/monsters/adult-blue-dragon,NaN,NaN
4,4,5f2329ad0b1bb138c59411f2,adult-brass-dragon,Adult Brass Dragon,Huge,dragon,NaN,chaotic good,18,172,...,[],"{'blindsight': '60 ft.', 'darkvision': '120 ft...","Common, Draconic",13.00,1,"[{'name': 'Multiattack', 'desc': 'The dragon c...",0,/api/monsters/adult-brass-dragon,NaN,NaN

In [447]:
data.describe()

,Unnamed: 0,armor_class,hit_points,strength,dexterity,constitution,intelligence,wisdom,charisma,challenge_rating,special_abilities,legendary_actions
count,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000
mean,160.500000,14.031056,81.291925,15.161491,12.624224,15.080745,7.754658,11.686335,9.683230,4.543090,0.826087,0.090062
std,93.097619,3.256285,99.425430,6.736612,3.202185,4.506105,5.704460,2.934020,5.789584,5.892224,0.379625,0.286716
min,0.000000,5.000000,1.000000,1.000000,1.000000,8.000000,1.000000,3.000000,1.000000,0.000000,0.000000,0.000000
25%,80.250000,12.000000,18.250000,11.000000,10.000000,12.000000,2.000000,10.000000,5.000000,0.500000,1.000000,0.000000
50%,160.500000,13.000000,45.000000,16.000000,13.000000,14.000000,7.000000,12.000000,8.000000,2.000000,1.000000,0.000000
75%,240.750000,17.000000,114.000000,19.000000,15.000000,18.000000,12.000000,13.000000,14.000000,6.000000,1.000000,0.000000
max,321.000000,25.000000,676.000000,30.000000,28.000000,30.000000,25.000000,25.000000,30.000000,30.000000,1.000000,1.000000

In [448]:
train1 = data[['armor_class','hit_points','legendary_actions','special_abilities','strength','dexterity','constitution','intelligence','wisdom','charisma']]

In [449]:
train1.head()

,armor_class,hit_points,legendary_actions,special_abilities,strength,dexterity,constitution,intelligence,wisdom,charisma
0,17,135,1,1,21,9,15,18,15,18
1,10,9,0,1,10,10,10,10,14,11
2,19,195,1,1,23,14,21,14,13,17
3,19,225,1,1,25,10,23,16,15,19
4,18,172,0,1,23,10,21,14,13,17

In [450]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
labels = data['challenge_rating']

In [451]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(train1 , labels , test_size = 0.1,random_state =2)

In [452]:
reg.fit(x_train,y_train)
reg.score(x_test,y_test)

0.9533218838268848

In [453]:
y_pred = reg.predict(train1)

In [454]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 1.06656777e+01  9.06385861e-01  1.35310584e+01  1.53363311e+01
  9.70215428e+00  1.48585802e+01  1.38423382e+01  1.65989133e+01
  1.48087228e+01  1.64060460e+01  1.59282952e+01  1.29944404e+01
  4.49515833e+00  2.13337008e+01  2.59741246e+01  1.84308221e+01
  2.48662265e+01  2.14244802e+01  2.86582628e+01  2.27107325e+01
  2.85822479e+01  2.64139941e+01  1.91026782e+01  1.38338854e+01
  9.25981412e-01  1.40699801e+00  1.28599623e+00  6.29531019e+00
  5.03470904e+00  9.70095472e-01  3.36298513e+00  2.95906239e-02
  3.86390019e+00  4.02165263e-01  2.00840331e-01  1.43594465e+01
  8.77107427e-01  4.07336169e+00  6.88657490e+00  1.65841373e+00
 -2.12669651e-01  3.17127735e+00  8.09310330e+00  4.17475672e+00
  7.64981599e-01  2.60444421e+00  2.32049692e+00  2.08905922e+00
  6.10834924e-01  3.47357402e+00 -1.37549686e-01  8.48429640e+00
  1.51859782e+00  2.99042700e+00  1.70950102e+00  2.19617552e+00
  5.36376864e+00 -4.00468483e-01  1.63376918e-01  2.77607247e+00
  5.54059091e+00  5.50017412e+00  4.77074478e+00  5.85416718e+00
  4.17409499e+00  1.04772877e+01  1.04006295e+00 -3.08683608e-02
 -9.60921196e-02  2.38383187e+00  8.26613767e+00 -5.77097040e-01
  5.22200704e-01  1.88475164e+00  7.94023542e-01  5.18319829e-01
  2.05783898e+00  2.33218093e+00  2.79216770e-01  9.27267241e+00
  2.17681173e+00  9.95668577e+00  3.60810255e+00 -2.60637339e-01
  1.54317814e+01  3.69293434e-01  8.09385363e+00  1.41884662e+00
  2.77561838e+00  2.08176771e+00  2.64161574e+00  1.20421928e+00
  2.18839353e-01  6.68641922e+00  1.19321182e+01  3.37024097e+00
 -2.36772502e-01  8.80073155e+00  2.56488122e+00  3.90965494e+00
  5.11905017e+00  9.16116957e+00  4.31239374e+00  7.12333356e-01
  2.57639798e-01 -9.92624441e-01  6.93659579e+00  3.34641102e+00
  2.99557745e+00  1.95928727e+00  1.89716287e+00  6.55073255e-01
  7.05122591e+00  8.15032646e-01  7.05900632e-01  1.47547704e+00
 -3.55247732e-01  1.48295343e+00  2.74544845e-01  3.63169465e+00
  2.18668576e+00  2.93432905e+00 -3.02656963e-01  2.56949399e-01
  5.20043971e-01  1.89267244e+00  5.66254648e-01  1.96456290e+00
  1.53465638e+00  6.96939689e-01  1.44718944e-01 -1.07135318e-01
  2.14069936e+00  6.32955056e-01  5.75686072e+00  1.18864779e+00
  1.31900212e+00  1.55550686e+00 -3.12289750e-01  5.34394824e-01
  1.08128479e+00  2.75793897e+00  1.06204123e+01  5.92278957e+00
  1.15932654e+00 -5.61617917e-01  9.35927888e-01  4.67680361e+00
  5.86498444e+00  2.38184279e-01  3.34482031e+00  5.66431375e+00
  1.49241604e+00  2.83814632e+00  6.26066071e-01  1.42755522e+00
  8.45120961e+00  1.15665305e+01  3.96665332e+00  1.10741280e+00
 -1.74795860e-02  2.97409091e+00  6.98070983e+00  4.74205555e+00
  4.97804116e-01  1.84008300e+00  1.32958849e+00  9.13111040e+00
  1.74234091e+00  7.65540163e+00  1.80164470e-01  1.03784724e+01
  1.01710333e+00  1.90597059e+00  5.80103899e+00  1.00840274e+01
  2.74022304e-01  3.29660328e+00  3.55474185e+00 -8.29801363e-02
  2.57933387e+01  5.79977089e+00 -5.23596519e-01  1.16682869e+01
  1.07041159e+00 -1.00851062e+00  1.90988554e+00  3.38494400e+00
  1.07272506e+00  1.35169533e+00  6.05768754e+00  4.28180122e+00
  1.13771640e+01  2.82538427e-01  7.08968116e+00  1.24024392e+00
  2.55645177e+00  3.02214852e+00  4.57936623e+00  2.91917395e+00
  2.29857688e-02  2.09451345e+00  9.28953445e+00  1.11456703e+01
  7.16655404e+00  4.08240626e+00  1.47613686e+00  7.79419290e-01
  2.59044224e-01  1.94274049e+00  2.82059356e+00  6.32480941e+00
  1.70425885e+00  6.40737954e+00 -5.90187139e-01  3.08840045e+00
  4.40094981e-01  3.77555854e+00  1.57274461e+00  1.65989044e+01
  1.31813034e+01  3.32528962e+00 -5.42099360e-02  2.08758281e+00
 -2.42753762e-01  2.94643877e+00  1.83520123e+00  1.05150338e+01
  5.83573880e-01 -6.02193395e-01  7.16146256e+00 -6.22353249e-01
 -3.51548977e-01  4.64617874e+00  6.43839927e-01  9.23465961e+00
  1.71327278e+00 -4.07033988e-01  1.01412552e+01  6.39101222e+00
 -4.48077602e-01  1.53825587e+00  2.36829139e+00  2.21590459e+00
  4.81581011e+00  2.02319195e+00 -1.26715834e+00  1.98969972e+00
  3.92276143e+00 -6.76187328e-01  1.25892641e+00  6.08284337e+00
  7.36425923e+00 -1.72453164e+00  3.54367681e+00  1.16644522e+00
  1.91785868e+01  1.68863036e+00 -5.48052108e-01  5.34715129e+00
  1.89918650e+00  1.92849715e+00  1.08634089e+00 -3.12327035e-01
  7.52663528e+00  8.61872960e+00  1.21984684e+01  4.38225941e+00
  8.49383068e-01  2.04446691e-01  2.04446691e-01  2.04446691e-01
  1.39002239e+00 -1.75122093e-02  2.19613289e-02  4.95664961e-01
  2.04446691e-01  2.04446691e-01  3.18344005e+01  1.95237625e+00
  1.67539078e+00  8.57817974e+00  9.89362424e-01  4.09788159e+00
  5.12835738e+00  5.57142255e+00  7.12799876e+00  1.16367090e+01
  4.84069576e+00  3.58826973e+00 -1.61488506e+00  6.19482708e+00
  4.00312546e-01  4.97151452e-01  5.56047183e-01  5.51154908e+00
 -4.81352257e-02  6.42023240e+00  3.94164132e+00  2.30761818e+00
  6.14303304e+00  3.15037699e+00  1.57036294e+00  3.44741656e+00
  3.65479711e+00  3.71260028e+00  7.41676975e-01  1.64520343e+00
  4.95266441e+00  4.86183495e+00  6.08806115e+00  7.01827738e+00
  8.38794549e+00  5.93243099e+00  8.27229911e+00  7.18795315e+00
  1.01358239e+01  8.18569165e+00  9.27391014e+00  8.90640949e+00
  6.54157603e+00  3.26193743e-01]

In [455]:
new_pred = reg.predict(train1[:10])

In [456]:
new_pred

array([10.66567765,  0.90638586, 13.53105838, 15.33633108,  9.70215428,
       14.85858024, 13.84233822, 16.59891331, 14.80872285, 16.40604605])

In [457]:
data[:10][['challenge_rating','armor_class','hit_points','legendary_actions','special_abilities','strength','dexterity','constitution','intelligence','wisdom','charisma']]
#train1[:10]

,challenge_rating,armor_class,hit_points,legendary_actions,special_abilities,strength,dexterity,constitution,intelligence,wisdom,charisma
0,10.00,17,135,1,1,21,9,15,18,15,18
1,0.25,10,9,0,1,10,10,10,10,14,11
2,14.00,19,195,1,1,23,14,21,14,13,17
3,16.00,19,225,1,1,25,10,23,16,15,19
4,13.00,18,172,0,1,23,10,21,14,13,17
5,15.00,19,212,1,1,25,10,23,16,15,19
6,14.00,18,184,1,1,23,12,21,18,15,17
7,17.00,19,256,1,1,27,14,25,16,15,24
8,15.00,19,207,1,1,23,12,21,18,15,17
9,17.00,19,256,1,1,27,10,25,16,13,21

In [458]:
train1['hit_points'].describe()

count    322.000000
mean      81.291925
std       99.425430
min        1.000000
25%       18.250000
50%       45.000000
75%      114.000000
max      676.000000
Name: hit_points, dtype: float64

In [459]:
output = data.copy(deep=True)

In [460]:
output[:10][['challenge_rating','armor_class','hit_points','legendary_actions','special_abilities','strength','dexterity','constitution','intelligence','wisdom','charisma']]

,challenge_rating,armor_class,hit_points,legendary_actions,special_abilities,strength,dexterity,constitution,intelligence,wisdom,charisma
0,10.00,17,135,1,1,21,9,15,18,15,18
1,0.25,10,9,0,1,10,10,10,10,14,11
2,14.00,19,195,1,1,23,14,21,14,13,17
3,16.00,19,225,1,1,25,10,23,16,15,19
4,13.00,18,172,0,1,23,10,21,14,13,17
5,15.00,19,212,1,1,25,10,23,16,15,19
6,14.00,18,184,1,1,23,12,21,18,15,17
7,17.00,19,256,1,1,27,14,25,16,15,24
8,15.00,19,207,1,1,23,12,21,18,15,17
9,17.00,19,256,1,1,27,10,25,16,13,21

In [461]:
output["guessed_CR"] = reg.predict(output[['armor_class','hit_points','legendary_actions','special_abilities','strength','dexterity','constitution','intelligence','wisdom','charisma']])

In [462]:
output[['guessed_CR', 'challenge_rating','armor_class','hit_points','legendary_actions','special_abilities','strength','dexterity','constitution','intelligence','wisdom','charisma']].head(10)

,guessed_CR,challenge_rating,armor_class,hit_points,legendary_actions,special_abilities,strength,dexterity,constitution,intelligence,wisdom,charisma
0,10.665678,10.00,17,135,1,1,21,9,15,18,15,18
1,0.906386,0.25,10,9,0,1,10,10,10,10,14,11
2,13.531058,14.00,19,195,1,1,23,14,21,14,13,17
3,15.336331,16.00,19,225,1,1,25,10,23,16,15,19
4,9.702154,13.00,18,172,0,1,23,10,21,14,13,17
5,14.858580,15.00,19,212,1,1,25,10,23,16,15,19
6,13.842338,14.00,18,184,1,1,23,12,21,18,15,17
7,16.598913,17.00,19,256,1,1,27,14,25,16,15,24
8,14.808723,15.00,19,207,1,1,23,12,21,18,15,17
9,16.406046,17.00,19,256,1,1,27,10,25,16,13,21

In [463]:
output['round_guessed_CR'] = output['guessed_CR'] .round()

In [473]:
output[['round_guessed_CR', 'challenge_rating','armor_class','hit_points','legendary_actions','special_abilities','strength','dexterity','constitution','intelligence','wisdom','charisma']].head(20)

,round_guessed_CR,challenge_rating,armor_class,hit_points,legendary_actions,special_abilities,strength,dexterity,constitution,intelligence,wisdom,charisma
0,11.0,10.00,17,135,1,1,21,9,15,18,15,18
1,1.0,0.25,10,9,0,1,10,10,10,10,14,11
2,14.0,14.00,19,195,1,1,23,14,21,14,13,17
3,15.0,16.00,19,225,1,1,25,10,23,16,15,19
4,10.0,13.00,18,172,0,1,23,10,21,14,13,17
5,15.0,15.00,19,212,1,1,25,10,23,16,15,19
6,14.0,14.00,18,184,1,1,23,12,21,18,15,17
7,17.0,17.00,19,256,1,1,27,14,25,16,15,24
8,15.0,15.00,19,207,1,1,23,12,21,18,15,17
9,16.0,17.00,19,256,1,1,27,10,25,16,13,21
10,16.0,16.00,19,243,1,1,27,10,25,16,13,21
11,13.0,13.00,18,200,1,1,22,10,22,8,12,12
12,4.0,5.00,15,90,0,1,14,20,14,6,10,6
13,21.0,21.00,22,367,1,1,27,14,25,16,15,19
14,26.0,23.00,22,481,1,0,29,10,27,18,17,21
15,18.0,20.00,20,297,1,1,27,10,25,16,15,19
16,25.0,22.00,22,444,1,1,29,10,27,18,17,21
17,21.0,21.00,21,350,1,1,27,12,25,20,17,19
18,29.0,24.00,22,546,1,1,30,14,29,18,17,28
19,23.0,22.00,21,385,1,1,27,12,25,20,17,19

In [474]:
output[['round_guessed_CR', 'challenge_rating','name',]].head(20)

    round_guessed_CR  challenge_rating                   name
0               11.0             10.00                Aboleth
1                1.0              0.25                Acolyte
2               14.0             14.00     Adult Black Dragon
3               15.0             16.00      Adult Blue Dragon
4               10.0             13.00     Adult Brass Dragon
5               15.0             15.00    Adult Bronze Dragon
6               14.0             14.00    Adult Copper Dragon
7               17.0             17.00      Adult Gold Dragon
8               15.0             15.00     Adult Green Dragon
9               16.0             17.00       Adult Red Dragon
10              16.0             16.00    Adult Silver Dragon
11              13.0             13.00     Adult White Dragon
12               4.0              5.00          Air Elemental
13              21.0             21.00   Ancient Black Dragon
14              26.0             23.00    Ancient Blue Dragon
15              18.0             20.00   Ancient Brass Dragon
16              25.0             22.00  Ancient Bronze Dragon
17              21.0             21.00  Ancient Copper Dragon
18              29.0             24.00    Ancient Gold Dragon
19              23.0             22.00   Ancient Green Dragon

In [465]:
output['round_guessed_CR'].describe()

count    322.000000
mean       4.555901
std        5.678152
min       -2.000000
25%        1.000000
50%        3.000000
75%        6.000000
max       32.000000
Name: round_guessed_CR, dtype: float64

In [466]:
output['challenge_rating'].describe()

count    322.000000
mean       4.543090
std        5.892224
min        0.000000
25%        0.500000
50%        2.000000
75%        6.000000
max       30.000000
Name: challenge_rating, dtype: float64

In [467]:
output[output.round_guessed_CR.values<0]

,Unnamed: 0,_id,index,name,size,type,subtype,alignment,armor_class,hit_points,...,languages,challenge_rating,special_abilities,actions,legendary_actions,url,reactions,other_speeds,guessed_CR,round_guessed_CR
71,71,5f2329ae0b1bb138c5941234,crab,Crab,Tiny,beast,NaN,unaligned,11,2,...,NaN,0.00,1,"[{'name': 'Claw', 'desc': 'Melee Weapon Attack...",0,/api/monsters/crab,NaN,NaN,-0.577097,-1.0
105,105,5f2329ae0b1bb138c5941256,frog,Frog,Tiny,beast,NaN,unaligned,11,1,...,NaN,0.00,1,NaN,0,/api/monsters/frog,NaN,NaN,-0.992624,-1.0
145,145,5f2329ae0b1bb138c594127f,goat,Goat,Medium,beast,NaN,unaligned,10,4,...,NaN,0.00,1,"[{'name': 'Ram', 'desc': 'Melee Weapon Attack:...",0,/api/monsters/goat,NaN,NaN,-0.561618,-1.0
182,182,5f2329ae0b1bb138c59412a4,lemure,Lemure,Medium,fiend,devil,lawful evil,7,13,...,understands infernal but can't speak,0.00,1,"[{'name': 'Fist', 'desc': 'Melee Weapon Attack...",0,/api/monsters/lemure,NaN,NaN,-0.523597,-1.0
185,185,5f2329ae0b1bb138c59412a6,lizard,Lizard,Tiny,beast,NaN,unaligned,10,2,...,NaN,0.00,0,"[{'name': 'Bite', 'desc': 'Melee Weapon Attack...",0,/api/monsters/lizard,NaN,NaN,-1.008511,-1.0
214,214,5f2329ae0b1bb138c59412c4,owl,Owl,Tiny,beast,NaN,unaligned,11,1,...,NaN,0.00,1,"[{'name': 'Talons', 'desc': 'Melee Weapon Atta...",0,/api/monsters/owl,NaN,NaN,-0.590187,-1.0
229,229,5f2329ae0b1bb138c59412d2,quipper,Quipper,Tiny,beast,NaN,unaligned,13,1,...,NaN,0.00,1,"[{'name': 'Bite', 'desc': 'Melee Weapon Attack...",0,/api/monsters/quipper,NaN,NaN,-0.602193,-1.0
231,231,5f2329ae0b1bb138c59412d4,rat,Rat,Tiny,beast,NaN,unaligned,10,1,...,NaN,0.00,1,"[{'name': 'Bite', 'desc': 'Melee Weapon Attack...",0,/api/monsters/rat,NaN,NaN,-0.622353,-1.0
246,246,5f2329ae0b1bb138c59412e3,scorpion,Scorpion,Tiny,beast,NaN,unaligned,11,1,...,NaN,0.00,0,"[{'name': 'Sting', 'desc': 'Melee Weapon Attac...",0,/api/monsters/scorpion,NaN,NaN,-1.267158,-1.0
249,249,5f2329ae0b1bb138c59412e6,sea-horse,Sea Horse,Tiny,beast,NaN,unaligned,11,1,...,NaN,0.00,1,NaN,0,/api/monsters/sea-horse,NaN,NaN,-0.676187,-1.0
253,253,5f2329ae0b1bb138c59412ea,shrieker,Shrieker,Medium,plant,NaN,unaligned,5,13,...,NaN,0.00,1,"[{'name': 'Shriek', 'desc': ""When bright light...",0,/api/monsters/shrieker,NaN,NaN,-1.724532,-2.0
258,258,5f2329ae0b1bb138c59412ef,spider,Spider,Tiny,beast,NaN,unaligned,12,1,...,NaN,0.00,1,"[{'name': 'Bite', 'desc': 'Melee Weapon Attack...",0,/api/monsters/spider,NaN,NaN,-0.548052,-1.0
290,290,5f2329ae0b1bb138c594130f,violet-fungus,Violet Fungus,Medium,plant,NaN,unaligned,5,18,...,NaN,0.25,1,"[{'name': 'Multiattack', 'desc': 'The fungus m...",0,/api/monsters/violet-fungus,NaN,NaN,-1.614885,-2.0

In [468]:
output[output.round_guessed_CR.values>30]

,Unnamed: 0,_id,index,name,size,type,subtype,alignment,armor_class,hit_points,...,languages,challenge_rating,special_abilities,actions,legendary_actions,url,reactions,other_speeds,guessed_CR,round_guessed_CR
278,278,5f2329ae0b1bb138c5941305,tarrasque,Tarrasque,Gargantuan,monstrosity,titan,unaligned,25,676,...,NaN,30.0,1,"[{'name': 'Multiattack', 'desc': 'The tarrasqu...",1,/api/monsters/tarrasque,NaN,NaN,31.8344,32.0

In [469]:
output['CR_diff'] = output['round_guessed_CR']-output['challenge_rating']

In [470]:
output[output.CR_diff.values>1].count()

Unnamed: 0                41
_id                       41
index                     41
name                      41
size                      41
type                      41
subtype                   15
alignment                 41
armor_class               41
hit_points                41
hit_dice                  41
speed                     41
strength                  41
dexterity                 41
constitution              41
intelligence              41
wisdom                    41
charisma                  41
proficiencies             41
damage_vulnerabilities    41
damage_resistances        41
damage_immunities         41
condition_immunities      41
senses                    41
languages                 39
challenge_rating          41
special_abilities         41
actions                   41
legendary_actions         41
url                       41
reactions                  1
other_speeds               1
guessed_CR                41
round_guessed_CR          41
CR_diff                   41
dtype: int64

In [471]:
output[output.CR_diff.values>=2].count()

Unnamed: 0                27
_id                       27
index                     27
name                      27
size                      27
type                      27
subtype                    8
alignment                 27
armor_class               27
hit_points                27
hit_dice                  27
speed                     27
strength                  27
dexterity                 27
constitution              27
intelligence              27
wisdom                    27
charisma                  27
proficiencies             27
damage_vulnerabilities    27
damage_resistances        27
damage_immunities         27
condition_immunities      27
senses                    27
languages                 26
challenge_rating          27
special_abilities         27
actions                   27
legendary_actions         27
url                       27
reactions                  1
other_speeds               1
guessed_CR                27
round_guessed_CR          27
CR_diff                   27
dtype: int64

In [472]:
output[output.CR_diff.values>=2]

,Unnamed: 0,_id,index,name,size,type,subtype,alignment,armor_class,hit_points,...,challenge_rating,special_abilities,actions,legendary_actions,url,reactions,other_speeds,guessed_CR,round_guessed_CR,CR_diff
14,14,5f2329ad0b1bb138c59411fb,ancient-blue-dragon,Ancient Blue Dragon,Gargantuan,dragon,NaN,lawful evil,22,481,...,23.0,0,"[{'name': 'Multiattack', 'desc': 'The dragon c...",1,/api/monsters/ancient-blue-dragon,NaN,NaN,25.974125,26.0,3.0
16,16,5f2329ad0b1bb138c59411fe,ancient-bronze-dragon,Ancient Bronze Dragon,Gargantuan,dragon,NaN,lawful good,22,444,...,22.0,1,"[{'name': 'Multiattack', 'desc': 'The dragon c...",1,/api/monsters/ancient-bronze-dragon,NaN,NaN,24.866226,25.0,3.0
18,18,5f2329ad0b1bb138c5941200,ancient-gold-dragon,Ancient Gold Dragon,Gargantuan,dragon,NaN,lawful good,22,546,...,24.0,1,"[{'name': 'Multiattack', 'desc': 'The dragon c...",1,/api/monsters/ancient-gold-dragon,NaN,NaN,28.658263,29.0,5.0
20,20,5f2329ad0b1bb138c5941202,ancient-red-dragon,Ancient Red Dragon,Gargantuan,dragon,NaN,chaotic evil,22,546,...,24.0,1,"[{'name': 'Multiattack', 'desc': 'The dragon c...",1,/api/monsters/ancient-red-dragon,NaN,NaN,28.582248,29.0,5.0
21,21,5f2329ad0b1bb138c5941204,ancient-silver-dragon,Ancient Silver Dragon,Gargantuan,dragon,NaN,lawful good,22,487,...,23.0,1,"[{'name': 'Multiattack', 'desc': 'The dragon c...",1,/api/monsters/ancient-silver-dragon,NaN,NaN,26.413994,26.0,3.0
32,32,5f2329ad0b1bb138c594120e,azer,Azer,Medium,elemental,NaN,lawful neutral,17,39,...,2.0,1,"[{'name': 'Warhammer', 'desc': 'Melee Weapon A...",0,/api/monsters/azer,NaN,NaN,3.863900,4.0,2.0
37,37,5f2329ad0b1bb138c5941213,bandit-captain,Bandit Captain,Medium,humanoid,any race,any non-lawful alignment,15,65,...,2.0,0,"[{'name': 'Multiattack', 'desc': 'The captain ...",0,/api/monsters/bandit-captain,"[{'name': 'Parry', 'desc': 'The captain adds 2...",NaN,4.073362,4.0,2.0
38,38,5f2329ad0b1bb138c5941214,barbed-devil,Barbed Devil,Medium,fiend,devil,lawful evil,15,110,...,5.0,1,"[{'name': 'Multiattack', 'desc': 'The devil ma...",0,/api/monsters/barbed-devil,NaN,NaN,6.886575,7.0,2.0
43,43,5f2329ad0b1bb138c5941218,berserker,Berserker,Medium,humanoid,any race,any chaotic alignment,13,67,...,2.0,1,"[{'name': 'Greataxe', 'desc': 'Melee Weapon At...",0,/api/monsters/berserker,NaN,NaN,4.174757,4.0,2.0
70,70,5f2329ae0b1bb138c5941236,couatl,Couatl,Medium,celestial,NaN,lawful good,19,97,...,4.0,1,"[{'name': 'Bite', 'desc': 'Melee Weapon Attack...",0,/api/monsters/couatl,NaN,NaN,8.266138,8.0,4.0
86,86,5f2329ae0b1bb138c5941245,drider,Drider,Large,monstrosity,NaN,chaotic evil,19,123,...,6.0,1,"[{'name': 'Multiattack', 'desc': 'The drider m...",0,/api/monsters/drider,NaN,NaN,8.093854,8.0,2.0
90,90,5f2329ae0b1bb138c5941247,duergar,Duergar,Medium,humanoid,dwarf,lawful evil,16,26,...,1.0,1,"[{'name': 'Enlarge', 'desc': 'For 1 minute, th...",0,/api/monsters/duergar,NaN,NaN,2.641616,3.0,2.0
93,93,5f2329ae0b1bb138c594124b,earth-elemental,Earth Elemental,Large,elemental,NaN,neutral,17,126,...,5.0,1,"[{'name': 'Multiattack', 'desc': 'The elementa...",0,/api/monsters/earth-elemental,NaN,NaN,6.686419,7.0,2.0
142,142,5f2329ae0b1bb138c594127b,glabrezu,Glabrezu,Large,fiend,demon,chaotic evil,17,157,...,9.0,1,"[{'name': 'Multiattack', 'desc': 'The glabrezu...",0,/api/monsters/glabrezu,NaN,NaN,10.620412,11.0,2.0
147,147,5f2329ae0b1bb138c5941281,gold-dragon-wyrmling,Gold Dragon Wyrmling,Medium,dragon,NaN,lawful good,17,60,...,3.0,1,"[{'name': 'Bite', 'desc': 'Melee Weapon Attack...",0,/api/monsters/gold-dragon-wyrmling,NaN,NaN,4.676804,5.0,2.0
151,151,5f2329ae0b1bb138c5941286,green-hag,Green Hag,Medium,fey,NaN,neutral evil,17,82,...,3.0,1,"[{'name': 'Claws', 'desc': 'Melee Weapon Attac...",0,/api/monsters/green-hag,NaN,NaN,5.664314,6.0,3.0
180,180,5f2329ae0b1bb138c59412a3,kraken,Kraken,Gargantuan,monstrosity,titan,chaotic evil,18,472,...,23.0,1,"[{'name': 'Multiattack', 'desc': 'The kraken m...",1,/api/monsters/kraken,NaN,NaN,25.793339,26.0,3.0
181,181,5f2329ae0b1bb138c59412a2,lamia,Lamia,Large,monstrosity,NaN,chaotic evil,13,97,...,4.0,1,"[{'name': 'Multiattack', 'desc': 'The lamia ma...",0,/api/monsters/lamia,NaN,NaN,5.799771,6.0,2.0
198,198,5f2329ae0b1bb138c59412b4,minotaur,Minotaur,Large,monstrosity,NaN,chaotic evil,14,76,...,3.0,1,"[{'name': 'Greataxe', 'desc': 'Melee Weapon At...",0,/api/monsters/minotaur,NaN,NaN,4.579366,5.0,2.0
204,204,5f2329ae0b1bb138c59412bb,night-hag,Night Hag,Medium,fiend,NaN,neutral evil,17,112,...,5.0,1,"[{'name': 'Claws (Hag Form Only)', 'desc': 'Me...",0,/api/monsters/night-hag,NaN,NaN,7.166554,7.0,2.0
217,217,5f2329ae0b1bb138c59412c8,pegasus,Pegasus,Large,celestial,NaN,chaotic good,12,59,...,2.0,0,"[{'name': 'Hooves', 'desc': 'Melee Weapon Atta...",0,/api/monsters/pegasus,NaN,NaN,3.775559,4.0,2.0
248,248,5f2329ae0b1bb138c59412e9,sea-hag,Sea Hag,Medium,fey,NaN,chaotic evil,14,52,...,2.0,1,"[{'name': 'Claws', 'desc': 'Melee Weapon Attac...",0,/api/monsters/sea-hag,NaN,NaN,3.922761,4.0,2.0
254,254,5f2329ae0b1bb138c59412ed,silver-dragon-wyrmling,Silver Dragon Wyrmling,Medium,dragon,NaN,lawful good,17,45,...,2.0,0,"[{'name': 'Bite', 'desc': 'Melee Weapon Attack...",0,/api/monsters/silver-dragon-wyrmling,NaN,NaN,3.543677,4.0,2.0
278,278,5f2329ae0b1bb138c5941305,tarrasque,Tarrasque,Gargantuan,monstrosity,titan,unaligned,25,676,...,30.0,1,"[{'name': 'Multiattack', 'desc': 'The tarrasqu...",1,/api/monsters/tarrasque,NaN,NaN,31.834400,32.0,2.0
286,286,5f2329ae0b1bb138c594130c,unicorn,Unicorn,Large,celestial,NaN,lawful good,12,67,...,5.0,1,"[{'name': 'Multiattack', 'desc': 'The unicorn ...",1,/api/monsters/unicorn,NaN,NaN,7.127999,7.0,2.0
300,300,5f2329ae0b1bb138c5941319,weretiger,Weretiger,Medium,humanoid,human,neutral,12,120,...,4.0,1,[{'name': 'Multiattack (Humanoid or Hybrid For...,0,/api/monsters/weretiger,NaN,"[{'form': 'tiger', 'speed': {'walk': '40 ft.'}}]",6.143033,6.0,2.0
304,304,5f2329ae0b1bb138c594131e,will-o-wisp,Will-o'-Wisp,Tiny,undead,NaN,chaotic evil,19,22,...,2.0,1,"[{'name': 'Shock', 'desc': 'Melee Spell Attack...",0,/api/monsters/will-o-wisp,NaN,NaN,3.654797,4.0,2.0